#!/bin/bash

## NOTE: Uncomment lines 16-18 to run the configurations after specifying EXEPATH below.

EXEPATH=<PATH TO ANALYSIS>

for i in AllInfo Lattice UTfit
do
        cd ${i}
        for j in NP_CA NP_CA_1 NP_CA_2 NP_CP NP_CP_1 NP_CP_2 NP_CS NP_CS_1 NP_CS_2 NP_CS_CP NP_CS_CP_1 NP_CS_CP_2 NP_CS_CP_3 NP_CS_CP_4 NP_CV NP_CV_1 NP_CV_2 NP_CV_CA NP_CV_CA_1 NP_CV_CA_2 NP_CV_CA_3 NP_CV_CA_4
        do
                cp ../MonteCarlo.conf ${j}/config
                cp config_BGL_${i}/*.conf ${j}/config
                cd ${j}
                rm -f *.out *.err log.txt *.pdf. *.root *.tex *.txt
#                ln -sf ${EXEPATH} .
#                sed -e "s#NAME#BGL-${i}-${j}#g" ../../sbatch.sh sbatch.sh
#                sbatch sbatch.sh
                cd ..
        done
        cd ..
done
