#!/bin/bash
rm -rf data
mkdir data

function getData {
	rm -f stats
	count=0
	for i in 1 2 3 4 5
	do
		echo "LQBIN${i}:" >> stats
		echo "Experimental Correlation Matrix:" >> stats
		cat LQBIN${i}/conf*/Obs*LQ* | grep "C_LQ" | grep "#" | sed -e "s/# //" -e "s/C_LQ[1-9]//" >> stats
		echo "Theoretical Correlation Matrix:" >> stats
		cat LQBIN${i}/Observables*/Stat* | grep " |" | awk '(NR >1){print}' | sed -e "s/ *[1-9] |//" -e "s/\([0-9]\)\(-\)/\1 -/g" -e "s/\([0-9]\)\(0\.\)/\1 0\./" >> stats
		cat LQBIN${i}/Observables*/Stat* | grep Observable | grep -v Observables > aa
		cat LQBIN${i}/Observables*/Stat* | grep +- > bb
		echo "Fit Statistics:" >> stats
		paste aa bb | grep "_LQ${i}\[" | sed -e 's/([^"]*"//' -e 's/\[[^:]*://' | awk '{print $1 "    " $5 "    " $7}' >> stats
		echo "Experimental Numbers:" >> stats
		cat LQBIN${i}/conf_files/Observables_LQ.conf | grep "_LQ${i}" | grep -v "\-1." | grep MCMC | awk '{print $2 "    " $9 "    " $10}' >> stats
		echo "   " >> stats
		rm aa bb
		count=`wc -l stats | awk '{print $1}'`
		check=$((${i}*45))
		if [ "$count" -ne "$check" ]; then
			echo "ERROR in extracting data from LQBIN${i}"	
		fi	
	done


	echo "LQBIN6:" >> stats
	echo "Experimental Correlation Matrix:" >> stats
	cat FULL/conf*/Eight* | grep "C_LQ6" | grep "#" | sed -e "s/# //" -e "s/C_LQ6//" >> stats
	echo "Theoretical Correlation Matrix:" >> stats
	cat FULL/Observables*/Stat* | grep " |" | awk '(NR >1){print}' | sed -e "s/ *[1-9] |//" -e "s/\([0-9]\)\(-\)/\1 -/g" | awk -v n=9 'NR>n{print line[NR%n]};{line[NR%n]=$0}' >> stats
	cat FULL/Observables*/Stat* | grep Observable | grep -v Observables > aa
	cat FULL/Observables*/Stat* | grep +- > bb
	echo "Fit Statistics:" >> stats
	paste aa bb | grep "_LQ6\[" | sed -e 's/([^"]*"//' -e 's/\[[^:]*://' | awk '{print $1 "    " $5 "    " $7}' >> stats
	echo "Experimental Numbers:" >> stats
	cat FULL/conf_files/Eight* | grep "_LQ6" | grep -v "\-1." | grep MCMC | awk '{print $2 "    " $9 "    " $10}' >> stats
	echo "   " >> stats
	rm aa bb
	count=`wc -l stats | awk '{print $1}'`
	check=$((6*45))
	if [ "$count" -ne "$check" ]; then
		echo "ERROR in extracting data from LQBIN6"
	fi

        echo "BR:" >> stats
        echo "Fit Statistics:" >> stats
        for j in -LQ1 -LQ2 -LQ3 _BKstgamma
        do
                cat BR${j}/Observables*/Stat* | grep Observable | grep -v Observables > aa
                cat BR${j}/Observables*/Stat* | grep +- > bb
                paste aa bb | grep "BR${j}" | grep -v "LQ4" | grep -v "BR_e" | sed -e 's/([^"]*"//' -e 's/\[[^:]*://' -e "s/\"://" | awk '{print $1 "    " $5 "    " $7}' >> stats
        done

        echo "Experimental Numbers:" >> stats
        cat BR-LQ1/conf_files/Observables_LQ.conf | grep "BR" | awk '{print $2 "    " $9 "    " $10}' >> stats
        echo "   " >> stats
        rm aa bb
	
	echo "ee:" >> stats
	cat Obs_ee/Observables*/Stat* | grep Observable | grep -v Observables > aa
	cat Obs_ee/Observables*/Stat* | grep +- > bb
	echo "Fit Statistics:" >> stats
	paste aa bb | grep "_e" | sed -e 's/([^"]*"//' -e 's/\[[^:]*://' | awk '{print $1 "    " $5 "    " $7}' >> stats
	echo "Experimental Numbers:" >> stats
	cat Obs_ee/conf_files/Observables_LQ_ee.conf | grep "_e" | awk '{print $2 "    " $9 "    " $10}' >> stats
	echo "   " >> stats
	rm aa bb

	count=`wc -l stats | awk '{print $1}'`
	check=296
	if [ "$count" -ne "$check" ]; then
		echo "ERROR in extracting data from BR and/or ee"
	fi
}

rm -rf data
mkdir data

for k in KD NOKD FULLKD NOq4
do
	cd ${k}
	getData
	mv stats ../data/stats_${k}.txt
	cd ..
done

