#!/bin/bash
case `uname` in Darwin*) SEDi="sed -i ''";;
          *) SEDi="sed -i";; esac
for i in KD NOKD FULLKD NOq4
do
        cp makerun ${i}/.
        cp run_long.sh ${i}/.
        cd ${i}
        ${SEDi} -e "s/FOLDER/$i/" run_long.sh
        ./makerun
        cd ../
done
