#!/bin/bash
rm -rf FULL
mkdir FULL
cp -r conf_files FULL/.
cp run_long.sh FULL/run_long_FULL.sh
cd FULL
sed -i "" -e "/P_/s/## //" conf_files/Observables_LQ.conf
sed -i "" -e "/EightToNine.conf/s/#### //" conf_files/StandardModel.conf
sed -i "" -e "s/TAG/FULL/g" run_long_FULL.sh
# ln -s ~/NetBeansProjects/HEPfit/Analysis/dist/Release_MPI/GNU-Linux/analysis analysis
# qsub run_long_FULL.sh
cd ../

for i in 1 2 3 4 5
do
	rm -rf LQBIN${i}
	mkdir LQBIN${i}
	cp -r conf_files LQBIN${i}/.
	cp run_long.sh LQBIN${i}/run_long_LQBIN${i}.sh
	cd LQBIN${i}
	sed -i "" -e "/_LQ$i/s/^## //" -e "/_LQ$i/s/MCMC/noMCMC/" -e "/_LQ$i/s/weight/noweight/" -e "/_LQ$i/s/nono/no/g" conf_files/Observables_LQ.conf
	sed -i "" -e "/LQBIN$i/s/CorrelatedGaussianObservables/CorrelatedObservables/" conf_files/Observables_LQ.conf
	sed -i "" -e "/C_LQ$i/s/^/# /" conf_files/Observables_LQ.conf
	sed -i "" -e "s/TAG/LQBIN$i/g" run_long_LQBIN${i}.sh
	# ln -s ~/NetBeansProjects/HEPfit/Analysis/dist/Release_MPI/GNU-Linux/analysis
	# qsub run_long_LQBIN${i}.sh
	cd ../
done

rm -rf BR
mkdir BR
cp -r conf_files BR/.
cp run_long.sh BR/run_long_BR.sh
cd BR
sed -i "" -e "/BR-/s/MCMC/noMCMC/" -e "/BR-/s/weight/noweight/" conf_files/Observables_LQ.conf
sed -i "" -e "s/TAG/BR/g" run_long_BR.sh
# ln -s ~/NetBeansProjects/HEPfit/Analysis/dist/Release_MPI/GNU-Linux/analysis
# qsub run_long_BR.sh
cd ../

for i in 1 2 3
do
        rm -rf BR-LQ${i}
        mkdir BR-LQ${i}
        cp -r conf_files BR-LQ${i}/.
        cp run_long.sh BR-LQ${i}/run_long_BR-LQ${i}.sh
        cd BR-LQ${i}
        sed -i "" -e "/BR-LQ$i/s/MCMC/noMCMC/" -e "/BR-LQ$i/s/weight/noweight/" conf_files/Observables_LQ.conf
        sed -i "" -e "s/TAG/BR-LQ$i/g" run_long_BR-LQ${i}.sh
        # ln -s ~/NetBeansProjects/HEPfit/Analysis/dist/Release_MPI/GNU-Linux/analysis
        # qsub run_long_BR-LQ${i}.sh
        cd ../
done

rm -rf BR_BKstgamma
mkdir BR_BKstgamma
cp -r conf_files BR_BKstgamma/.
cp run_long.sh BR_BKstgamma/run_long_BR_BKstgamma.sh
cd BR_BKstgamma
sed -i "" -e "/BR_BKst/s/MCMC/noMCMC/" -e "/BR_BKst/s/weight/noweight/" conf_files/Observables_LQ.conf
sed -i "" -e "s/TAG/BR_BKstgamma/g" run_long_BR_BKstgamma.sh
# ln -s ~/NetBeansProjects/HEPfit/Analysis/dist/Release_MPI/GNU-Linux/analysis
# qsub run_long_BR_BKstgamma.sh
cd ../

rm -rf Obs_ee
mkdir Obs_ee
cp -r conf_files Obs_ee/.
cp run_long.sh Obs_ee/run_long_Obs_ee.sh
cd Obs_ee
sed -i "" -e "/BdKste/s/MCMC/noMCMC/" -e "/BdKste/s/weight/noweight/" conf_files/Observables_LQ_ee.conf
sed -i "" -e "s/TAG/Obs_ee/g" run_long_Obs_ee.sh
# ln -s ~/NetBeansProjects/HEPfit/Analysis/dist/Release_MPI/GNU-Linux/analysis
# qsub run_long_Obs_ee.sh
cd ../
