NPDF2
######################################################################
# Mandatory configuration files 
#---------------------------------------------------------------------
IncludeFile StandardModel.conf
IncludeFile Flavour.conf
IncludeFile UTfit.conf
IncludeFile UTfit_NP.conf
#
######################################################################
# Optional configuration files 
#---------------------------------------------------------------------
# IncludeFile GeneralSUSY.conf
# IncludeFile THDM.conf
#
######################################################################
# Model Parameters 
#               name        ave         errg        errf
#---------------------------------------------------------------------
### Parameters in NPDF2
ModelParameter  CepsK       0.          0.          2.
ModelParameter  CDMK        1.          0.          1.
ModelParameter  CBd         1.          0.          1.
ModelParameter  PhiBd       0.          0.          0.7
ModelParameter  CBs         1.          0.          1.
ModelParameter  PhiBs       0.          0.          0.7
#
######################################################################
Observable  CepsK      CepsK      #epsilon_{K}  1. -1.  noMCMC noweight
Observable  CDMK       CDMK       #DeltaM_{K}   1. -1.  noMCMC noweight
Observable  CBd        CBd        C_{B_d}      1. -1.  noMCMC noweight
Observable  PhiBd      PhiBd      #Phi_{B_d}      1. -1.  noMCMC noweight
Observable  CBs        CBs        C_{B_s}      1. -1.  noMCMC noweight
Observable  PhiBs      PhiBs      #Phi_{B_s}      1. -1.  noMCMC noweight
########################################################################
Observable2D  CBdvsPhiBd CBd  C_{B_d}    1. -1. noMCMC noweight PhiBd #Phi_{B_d} 1. -1.
Observable2D  CBsvsPhiBs CBs  C_{B_s}    1. -1. noMCMC noweight PhiBs #Phi_{B_s} 1. -1.
Observable2D  CDMKvsCepsK CDMK  C_{#DeltaM_{K}}    1. -1. noMCMC noweight CepsK C_{#epsilon_{K}} 1. -1.
