StandardModel
######################################################################
# Mandatory configuration files 
#---------------------------------------------------------------------
IncludeFile SM_parameters.conf
IncludeFile Flavour.conf
IncludeFile UTfit.conf
IncludeFile UTfit_SM.conf
#IncludeFile UTfit_NP.conf
#
######################################################################
# Optional configuration files 
#---------------------------------------------------------------------
# IncludeFile GeneralSUSY.conf
# IncludeFile THDM.conf
#
######################################################################
#Observable MtMSbar MtMSbar MtMSbar 1. -1. noMCMC noweight
#Observable Mw Mw Mw 0. 0. noMCMC noweight
