ModelParameter  BD1         0.765       0.025       0.
ModelParameter  BD2         0.647       0.024       0.
ModelParameter  BD3         0.989       0.053       0.
ModelParameter  BD4         0.977       0.055       0.
ModelParameter  BD5         1.049       0.092       0.
ModelParameter  BDscale     3.          0.          0.
ModelParameter  BDscheme    0.          0.          0.
######################################################################
# Delta F=2 observables
Observable  Phis_JPsiPhi Phis_JPsiPhi #beta_{s}           1. -1. MCMC weight -0.061   0.014  0.
ModelParameter  DmkSM              8.8         3.6             0.  
Observable  DmK      DmK      #Deltam_{K}  1. -1.  MCMC weight 5.293 0.09 0.
ModelParameter  tD          0.4103	0.	    0.
ModelParameter	MD	    1.86484	0.	    0.
ModelParameter	FD	    0.2115	0.0009	    0.	
ModelParameter  SM_M12D     0.005    0.          0.005
Observable  M12D        M12D    M_{12}^{D}  1. -1.  MCMC weight 0.005    0.0005          0.0
Observable  ArgD     ArgD     #phi^{M}_{2} 1. -1.  MCMC weight 1.9 1.6 0.
#Observable      ImADC2      ImADC2  Im(M_{12}^{D})  1. -1.  MCMC weight 0.01    0.          0.01
Observable Asl_s_PS	    Asl_s_PS	    A_{sl}^s	    1.	    -1.	    MCMC	  weight	-0.0006  0.0028 0.
Observable Asl_d_PS     Asl_d_PS        A_{sl}^d        1.      -1.     MCMC    weight  -0.0021  0.0017 0.    
