#!/bin/bash
############################################################################
# This is a script to create the runs necessary for Project Silent Night   #
# This one script will cover both SMEFT and WEFT both in KD and dispersion #
# Classification Level: For Her Majesty's eyes ONLY.                       #
# -- Ayan Paul (December 2018, Berlin)                                     #
############################################################################

EXEPATH=/home/apaul/NetBeansProjects/HEPfit/Analysis/dist/Debug_MPI/GNU-Linux/analysis
## BATCH is SLURM or CONDOR
BATCH="SLURM"

## BSM
## First lets make the ones in both KD and dispersion
## Directory Structure:
## -- WEFT                    --SMEFT                    --SM
##    |-- KD   --dispersion     |-- KD   --dispersion      |-- KD   --dispersion

# rm -rf WEFT SMEFT
mkdir -p  WEFT SMEFT

# First WEFT
cd WEFT
for hads in KD dispersion
do
    mkdir -p ${hads} && cd ${hads}
    for run in C9_22 C9_22_C9p_22 C9_22_C10p_22 C9p_22_C10_22 C9_22_C9_11
    do
	mkdir -p ${run} && cd ${run}
	cp -r ../../../config .
	sed -i.bak -e "s/## WEFT ## //" config/StandardModel.conf
	rm config/*NPSMEFTd6.conf
	if [ ${hads} == 'KD' ]; then
	    rm config/dispersion.conf
	    sed -i.bak -e "s/USEDISP/false/" -e "s/## KD ## //" config/StandardModel.conf
	elif [ ${hads} == 'dispersion' ]; then
	    rm config/*h_lambda.conf 
	    sed -i.bak -e "s/USEDISP/true/" -e "s/## DISP ## //" config/StandardModel.conf
	fi
	case ${run} in
	    C9_22)
		sed -i.bak -e "/C9_22/s/RANGE/10./" -e "s/RANGE/0./" config/WEFT.conf
		sed -i.bak -e "/C9_22/s/^# //" config/Observables_NP_WEFT.conf
		;;
	    C9_22_C9p_22)
		sed -i.bak -e "/C9_22/s/RANGE/10./;/C9p_22/s/RANGE/10./" -e "s/RANGE/0./" config/WEFT.conf
		sed -i.bak -e "/C9_22/s/^# //;/C9p_22/s/^# //" config/Observables_NP_WEFT.conf
		;;
	    C9_22_C10p_22)
		sed -i.bak -e "/C9_22/s/RANGE/10./;/C10p_22/s/RANGE/10./" -e "s/RANGE/0./" config/WEFT.conf
		sed -i.bak -e "/C9_22/s/^# //;/C10p_22/s/^# //" config/Observables_NP_WEFT.conf
		;;
	    C9p_22_C10_22)
		sed -i.bak -e "/C9p_22/s/RANGE/5./;/C10_22/s/RANGE/2./" -e "s/RANGE/0./" config/WEFT.conf
		sed -i.bak -e "/C9p_22/s/^# //;/C10_22/s/^# //" config/Observables_NP_WEFT.conf
		;;
	    C9_22_C9_11)
		sed -i.bak -e "/C9_22/s/RANGE/10./;/C9_11/s/RANGE/10./" -e "s/RANGE/0./" config/WEFT.conf
		sed -i.bak -e "/C9_22/s/^# //;/C9_11/s/^# //" config/Observables_NP_WEFT.conf
		;;
	esac
	rm -rf analysis *.txt *.out *.err analysis Observables *.pdf *.tex config/*.bak
	ln -s ${EXEPATH} .
	#./analysis config/StandardModel.conf --noMC
	if [ ${BATCH} == 'SLURM' ]; then
	    sed -e "s/NAME/${run}-${hads}/" ../../../sbatch.sh > sbatch.sh
	    sbatch sbatch.sh
	elif [ ${BATCH} == 'CONDOR' ]; then
	    sed -e "/FAME/s/NAME/${run}-${hads}/" ../../../submit_condor.sh > submit_condor.sh
	    cp ../../../mpi-wrap.sh .
	    condor_submit submit_condor.sh
	fi
	cd ..
    done
    cd ..
done
cd ..

# Then SMEFT
cd SMEFT
for hads in KD dispersion
do
    mkdir -p ${hads} && cd ${hads}
    for run in CLQ1_2223 CLQ1_2223_CLd_2223 CLQ1_2223_Ced_2223 C_all_22 C_all CLQ1_2223_CQe_2322 CLQ1_2223_CQe_2322_CLQ1_1123_CQe_2311
    do
	mkdir -p ${run} && cd ${run}
	cp -r ../../../config .
	sed -i.bak -e "s/## NPD6 ## //" config/StandardModel.conf
	rm config/*WEFT.conf
	if [ ${hads} == 'KD' ]; then
	    rm config/dispersion.conf
	    sed -i.bak -e "s/USEDISP/false/" -e "s/## KD ## //" config/StandardModel.conf
	elif [ ${hads} == 'dispersion' ]; then
	    rm config/*h_lambda.conf 
	    sed -i.bak -e "s/USEDISP/true/" -e "s/## DISP ## //" config/StandardModel.conf
	fi
	case ${run} in
	    CLQ1_2223)
		sed -i.bak -e "/CLQ1_2223/s/RANGE_2/2./" -e "s/RANGE_1/0./;s/RANGE_2/0./" config/NPSMEFTd6.conf
		sed -i.bak -e "/CLQ1_2223/s/^# //" config/Observables_NP_NPSMEFTd6.conf
		;;
	    CLQ1_2223_CLd_2223)
		sed -i.bak -e "/CLQ1_2223/s/RANGE_2/2./;/CLd_2223/s/RANGE_2/1.5/" -e "s/RANGE_1/0./;s/RANGE_2/0./" config/NPSMEFTd6.conf
		sed -i.bak -e "/CLQ1_2223/s/^# //;/CLd_2223/s/^# //" config/Observables_NP_NPSMEFTd6.conf
		;;
	    CLQ1_2223_Ced_2223)
		sed -i.bak -e "/CLQ1_2223/s/RANGE_2/2./;/Ced_2223/s/RANGE_2/10./" -e "s/RANGE_1/0./;s/RANGE_2/0./" config/NPSMEFTd6.conf
		sed -i.bak -e "/CLQ1_2223/s/^# //;/Ced_2223/s/^# //" config/Observables_NP_NPSMEFTd6.conf
		;;
	    C_all_22)
		sed -i.bak -e "/CLQ1_2223/s/RANGE_2/5./;/CLd_2223/s/RANGE_2/2./;/CLd_2223/s/0./-0.5/" -e "s/RANGE_2/5./" -e "s/RANGE_1/0./" config/NPSMEFTd6.conf
		sed -i.bak -e "/22/s/^# //" config/Observables_NP_NPSMEFTd6.conf
		;;
	    C_all)
		sed -i.bak -e "/CLQ1_2223/s/RANGE_2/5./;/CLd_2223/s/RANGE_2/2./;/CLd_2223/s/0./-0.5/;s/RANGE_1/10./;s/RANGE_2/10./;/CLQ1_1123/s/0./5./" config/NPSMEFTd6.conf
		sed -i.bak -e "24,36s/^# //" config/Observables_NP_NPSMEFTd6.conf
		;;
	    CLQ1_2223_CQe_2322)
		sed -i.bak -e "/CLQ1_2223/s/RANGE_2/2./;/CQe_2322/s/RANGE_2/2.5/" -e "s/RANGE_1/0./;s/RANGE_2/0./" config/NPSMEFTd6.conf
		sed -i.bak -e "/CLQ1_2223/s/^# //;/CQe_2322/s/^# //" config/Observables_NP_NPSMEFTd6.conf
		;;
	    CLQ1_2223_CQe_2322_CLQ1_1123_CQe_2311)
		sed -i.bak -e "/CLQ1_2223/s/RANGE_2/2./;/CQe_2322/s/RANGE_2/2.5/" -e "/CLQ1_1123/s/RANGE_1/5./;/CQe_2311/s/RANGE_1/10./" -e "s/RANGE_1/0./;s/RANGE_2/0./" config/NPSMEFTd6.conf
		sed -i.bak -e "/CLQ1_2223/s/^# //;/CQe_2322/s/^# //;/CLQ1_1123/s/^# //;/CQe_2311/s/^# //" config/Observables_NP_NPSMEFTd6.conf
		;;
	esac
	rm -rf analysis *.txt *.out *.err analysis Observables *.pdf *.tex config/*.bak
	ln -s ${EXEPATH} .
        #./analysis config/StandardModel.conf --noMC
	if [ ${BATCH} == 'SLURM' ]; then
	    sed -e "s/NAME/${run}-${hads}/" ../../../sbatch.sh > sbatch.sh
	    sbatch sbatch.sh
	elif [ ${BATCH} == 'CONDOR' ]; then
	    sed -e "/FAME/s/NAME/${run}-${hads}/" ../../../submit_condor.sh > submit_condor.sh
	    cp ../../../mpi-wrap.sh .
	    condor_submit submit_condor.sh
	fi
	cd ..
    done
    cd ..
done
cd ..

# Now for the KD only cases
# WEFT
cd WEFT
hads="KD"
cd ${hads}
for run in C10_22_C10p_22 C10_11 C9_11_C9p_11 C10_11_C10p_11 C9_11_C10p_11 C9p_11_C10_11
do
    mkdir -p ${run} && cd ${run}
    cp -r ../../../config .
    sed -i.bak -e "s/## WEFT ## //" config/StandardModel.conf
    rm config/*NPSMEFTd6.conf
    rm config/dispersion.conf
    sed -i.bak -e "s/USEDISP/false/" -e "s/## KD ## //" config/StandardModel.conf
    case ${run} in
	C10_22_C10p_22)
	    sed -i.bak -e "/C10_22/s/RANGE/2./;/C10p_22/s/RANGE/10./" -e "s/RANGE/0./" config/WEFT.conf
	    sed -i.bak -e "/C10_22/s/^# //;/C10p_22/s/^# //" config/Observables_NP_WEFT.conf
	    ;;
	C10_11)
	    sed -i.bak -e "/C10_11/s/RANGE/10./" -e "s/RANGE/0./" config/WEFT.conf
	    sed -i.bak -e "/C10_11/s/^# //" config/Observables_NP_WEFT.conf
	    ;;
	C9_11_C9p_11)
	    sed -i.bak -e "/C9_11/s/RANGE/2.5/;/C9_11/s/0./2.5/;/C9p_11/s/RANGE/2./;/C9p_11/s/0./-1./" -e "s/RANGE/0./" config/WEFT.conf
	    sed -i.bak -e "/C9_11/s/^# //;/C9p_11/s/^# //" config/Observables_NP_WEFT.conf
	    ;;
	C10_11_C10p_11)
	    sed -i.bak -e "/C10_11/s/RANGE/2.5/;/C10p_11/s/RANGE/2.5/" -e "s/RANGE/0./" config/WEFT.conf
	    sed -i.bak -e "/C10_11/s/^# //;/C10p_11/s/^# //" config/Observables_NP_WEFT.conf
	    ;;
	C9_11_C10p_11)
	    sed -i.bak -e "/C9_11/s/RANGE/10./;/C10p_11/s/RANGE/10./" -e "s/RANGE/0./" config/WEFT.conf
	    sed -i.bak -e "/C9_11/s/^# //;/C10p_11/s/^# //" config/Observables_NP_WEFT.conf
	    ;;
	C9p_11_C10_11)
	    sed -i.bak -e "/C9p_11/s/RANGE/10./;/C10_11/s/RANGE/10./" -e "s/RANGE/0./" config/WEFT.conf
	    sed -i.bak -e "/C9p_11/s/^# //;/C10_11/s/^# //" config/Observables_NP_WEFT.conf
	    ;;
    esac
    rm -rf analysis *.txt *.out *.err analysis Observables *.pdf *.tex config/*.bak
    ln -s ${EXEPATH} .
    #./analysis config/StandardModel.conf --noMC
    if [ ${BATCH} == 'SLURM' ]; then
	sed -e "s/NAME/${run}-${hads}/" ../../../sbatch.sh > sbatch.sh
	sbatch sbatch.sh
    elif [ ${BATCH} == 'CONDOR' ]; then
	sed -e "/FAME/s/NAME/${run}-${hads}/" ../../../submit_condor.sh > submit_condor.sh
	cp ../../../mpi-wrap.sh .
	condor_submit submit_condor.sh
    fi
    cd ..
done
cd ..
cd ..

# Finally SMEFT KD only cases
# SMEFT
cd SMEFT
hads="KD"
cd ${hads}
for run in CLQ1_1123_CLd_1123 CLQ1_1123_Ced_1123 CQe_2311_CLd_1123 CQe_2311_Ced_1123 C_all_11 CLQ1_1123_CQe_2311
do
    mkdir -p ${run} && cd ${run}
    cp -r ../../../config .
    sed -i.bak -e "s/## NPD6 ## //" config/StandardModel.conf
    rm config/*WEFT.conf
    rm config/dispersion.conf
    sed -i.bak -e "s/USEDISP/false/" -e "s/## KD ## //" config/StandardModel.conf
    case ${run} in
	CLQ1_1123_CLd_1123)
	    sed -i.bak -e "/CLQ1_1123/s/RANGE_1/2./;/CLQ1_1123/s/0./-1./;/CLd_1123/s/RANGE_1/10./" -e "s/RANGE_1/0./;s/RANGE_2/0./" config/NPSMEFTd6.conf
	    sed -i.bak -e "/CLQ1_1123/s/^# //;/CLd_1123/s/^# //" config/Observables_NP_NPSMEFTd6.conf
	    ;;
	CLQ1_1123_Ced_1123)
	    sed -i.bak -e "/CLQ1_1123/s/RANGE_1/10./;/Ced_1123/s/RANGE_1/10./;/CLQ1_1123/s/0./5./" -e "s/RANGE_1/0./;s/RANGE_2/0./" config/NPSMEFTd6.conf
	    sed -i.bak -e "/CLQ1_1123/s/^# //;/Ced_1123/s/^# //" config/Observables_NP_NPSMEFTd6.conf
	    ;;
	CQe_2311_CLd_1123)
	    sed -i.bak -e "/CQe_2311/s/RANGE_1/3./;/CQe_2311/s/0./2./;/CLd_1123/s/RANGE_1/10./" -e "s/RANGE_1/0./;s/RANGE_2/0./" config/NPSMEFTd6.conf
	    sed -i.bak -e "/CQe_2311/s/^# //;/CLd_1123/s/^# //" config/Observables_NP_NPSMEFTd6.conf
	    ;;
	CQe_2311_Ced_1123)
	    sed -i.bak -e "/CQe_2311/s/RANGE_1/10./;/Ced_1123/s/RANGE_1/10./" -e "s/RANGE_1/0./;s/RANGE_2/0./" config/NPSMEFTd6.conf
	    sed -i.bak -e "/CQe_2311/s/^# //;/Ced_1123/s/^# //" config/Observables_NP_NPSMEFTd6.conf
	    ;;
	C_all_11)
	    sed -i.bak -e "s/RANGE_1/10./;/CLQ1_1123/s/0./5./" -e "s/RANGE_2/0./" config/NPSMEFTd6.conf
	    sed -i.bak -e "/11/s/^# //" config/Observables_NP_NPSMEFTd6.conf
	    ;;
	CLQ1_1123_CQe_2311)
	    sed -i.bak -e "/CLQ1_1123/s/RANGE_1/5./;/CQe_2311/s/RANGE_1/10./" -e "s/RANGE_1/0./;s/RANGE_2/0./" config/NPSMEFTd6.conf
	    sed -i.bak -e "/CLQ1_1123/s/^# //;/CQe_2311/s/^# //" config/Observables_NP_NPSMEFTd6.conf
	    ;;
    esac
    rm -rf analysis *.txt *.out *.err analysis Observables *.pdf *.tex config/*.bak
    ln -s ${EXEPATH} .
    #./analysis config/StandardModel.conf --noMC
    if [ ${BATCH} == 'SLURM' ]; then
	sed -e "s/NAME/${run}-${hads}/" ../../../sbatch.sh > sbatch.sh
	sbatch sbatch.sh
    elif [ ${BATCH} == 'CONDOR' ]; then
	sed -e "/FAME/s/NAME/${run}-${hads}/" ../../../submit_condor.sh > submit_condor.sh
	cp ../../../mpi-wrap.sh .
	condor_submit submit_condor.sh
    fi
    cd ..
done
cd ..
cd ..


# SM
mkdir SM
cd SM
for hads in KD dispersion
do
    mkdir -p ${hads} && cd ${hads}
    for run in SM
    do
	mkdir -p ${run} && cd ${run}
	cp -r ../../../config .
	sed -i.bak -e "s/## StandardModel/StandardModel/" config/StandardModel.conf
	rm config/*NPSMEFTd6.conf
	rm config/*WEFT.conf
	if [ ${hads} == 'KD' ]; then
	    rm config/dispersion.conf
	    sed -i.bak -e "s/USEDISP/false/" -e "s/## KD ## //" config/StandardModel.conf
	elif [ ${hads} == 'dispersion' ]; then
	    rm config/*h_lambda.conf 
	    sed -i.bak -e "s/USEDISP/true/" -e "s/## DISP ## //" config/StandardModel.conf
	fi
	rm -rf analysis *.txt *.out *.err analysis Observables *.pdf *.tex config/*.bak
	ln -s ${EXEPATH} .
        #./analysis config/StandardModel.conf --noMC
	if [ ${BATCH} == 'SLURM' ]; then
	    sed -e "s/NAME/${run}-${hads}/" ../../../sbatch.sh > sbatch.sh
	    sbatch sbatch.sh
	elif [ ${BATCH} == 'CONDOR' ]; then
	    sed -e "/FAME/s/NAME/${run}-${hads}/" ../../../submit_condor.sh > submit_condor.sh
	    cp ../../../mpi-wrap.sh .
	    condor_submit submit_condor.sh
	fi
	cd ..
    done
    cd ..
done
cd ..
