######################################################################
# Model Parameters
#               name        ave         errg        errf
#---------------------------------------------------------------------
### Parameters for Flavour (Mandatory for all models)
#   scheme for bag parameters [NDR=0, HV=1, LRI=2]
### Meson massee, lifetimes and decay constants
ModelParameter  MBd         5.279       0.          0.
ModelParameter  tBd         1.520       0.          0.
ModelParameter  FBsoFBd     1.208       0.005       0.
ModelParameter  MBp         5.279       0.          0.
ModelParameter  tBp         1.638       0.          0.
ModelParameter  MBs         5.366       0.          0.
ModelParameter  tBs         1.515       0.004       0.
ModelParameter  DGs_Gs      0.126       0.006       0.
ModelParameter  FBs         0.2301      0.0012      0.
ModelParameter  MK0         0.4976      0.          0.
ModelParameter  tKl         5.116e4     0.          0.
ModelParameter  FK          0.1561      0.          0.
ModelParameter  MKp         0.4937      0.          0.
ModelParameter  tKp         1.2380e4    0.          0.
ModelParameter  MKstar      0.89581     0.          0.
ModelParameter  tKstar      1.          0.          0.
ModelParameter  FKstar      0.204       0.          0.
ModelParameter  MKstarP     0.89166     0.          0.
ModelParameter  FKstarp     0.159       0.          0.
ModelParameter  Mphi        1.019461    0.          0.
ModelParameter  tphi        1.          0.          0.
ModelParameter  Fphi        0.233       0.          0.
ModelParameter  Fphip       0.191       0.          0.
ModelParameter  xs_phi      0.0         0.          0.  # needed for B_s -> phi ll asymmetries (ONLY)
#
### CKM
ModelParameter  lambda      0.2251      0.0006      0.
ModelParameter  A           0.826       0.009       0.
ModelParameter  rhob        0.160       0.009       0.
ModelParameter  etab        0.350       0.011       0.
#
### Matching Scale
ModelParameter  muw         80.385      0.          0.
#
ModelParameter  lambdaB     0.350       0.          0.150
ModelParameter  alpha1kst   0.04        0.          0.03
ModelParameter  alpha2kst   0.11        0.          0.09
ModelParameter  alpha2phi   0.18        0.          0.08
ModelParameter  alpha1kp    0.06        0.          0.03
ModelParameter  alpha2kp    0.115       0.          0.
######################################################################
