/*
 * Copyright (C) 2015 HEPfit Collaboration
 * All rights reserved.
 *
 * For the licensing terms see doc/COPYING.
 */

#ifndef HEFFGMINUS2_H
#define	HEFFGMINUS2_H

#include "StandardModel.h"
#include "StandardModelMatching.h"
#include "WilsonCoefficient.h"

/**
 * @class Heffgminus2
 * @ingroup LeptonFlavour
 * @brief A class for calculating all the Wilson coefficients for the process \f$ (g-2)_{\mu} \f$ at one-loop. 
 * @author HEPfit Collaboration
 * @copyright GNU General Public License
 * @details The Heffgminus2 class aggregates the Wilson coefficients for the process \f$ (g-2)_{\mu} \f$ at one-loop generated by the model and sum them order by order.
 */
class Heffgminus2 {
public:
    /**
     * @brief The constructor of the class Heffgminus2.
     * @param[in] Wilson coefficient responsible for the process \f$ (g-2)_{\mu} \f$ at one-loop in the model analyzed
     */
    Heffgminus2(const StandardModel & SM_i);
    
    /**
     * 
     * @brief destructor of the class Heffgminus2.
     */
    virtual ~Heffgminus2();
    
    /**
     * @brief Computes the Wilson coefficients for the process \f$ (g-2)_{\mu} \f$ at one-loop.
     * @return returns the Wilson coefficients for the process
     */
    gslpp::vector<gslpp::complex>** ComputeCoeffgm2mu();

    /**
     * @brief Calls the model analyzed to calculate Wilson coefficients for the process \f$ (g-2)_{\mu} \f$ at one-loop.
     */   
    const StandardModel& GetModel() const {
        return model;
    }
    
private :
    /**
     * @brief Variable which stores the model information.
     */
    const StandardModel& model;

    /**
     * @brief Variable which stores the Wilson coefficient for \f$ (g-2)_{\mu} \f$ at one-loop.
     */
    WilsonCoefficient coeffgminus2mu;

};

#endif	/* HEFFGMINUS2_H */
