#! /bin/sh


# ---------------------------------------------------------------------
# This file contains some code from clhep-config and xft-config,
# copyright under GPL, resp. quasi-BSD, license by the authors of the
# clhep and xft projects.
# ---------------------------------------------------------------------


package="bat"
version="0.9.4.1"


# ---------------------------------------------------------------------
# From clhep-config:

# use the full name of this script to get the current path
configpath=`dirname ${0}`
# check for a leading slash to determine if this is a relative path
firstc=`expr "${configpath}" : "^\/"`
calldir=`pwd`
if [ ${firstc} -eq 0 ]
then
   cd ${calldir}/${configpath}; newpath=`pwd`
   binpath=${newpath}
else
   binpath=${configpath}
fi

# ---------------------------------------------------------------------

prefix="/home/beaujean/.local/sw/bat/linux-ubuntu-14.04-x86_64/master"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"

if [ "${bindir}" != "${binpath}" ] ; then
	# package has been relocated from original install path
	prefix=`dirname ${binpath}`
	exec_prefix="${prefix}"
	bindir="${binpath}"
fi

libdir="${exec_prefix}/lib"
includedir="${prefix}/include"

# ---------------------------------------------------------------------


usage()
{
  cat <<EOF
Usage: bat-config [OPTIONS]
General options:
    --prefix
    --version
    --libs
    --cflags
EOF
    exit $1
}

if test $# -eq 0 ; then
  usage 1 1>&2
fi


while test $# -gt 0 ; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
  --help)
	usage 0
	;;
  --prefix)
    echo_prefix=yes
    ;;
  --version)
    echo $version
    exit 0
    ;;
  --cflags)
    echo_cflags=yes
    ;;
  --libs)
    echo_libs=yes
    ;;
  *)
    usage 1 1>&2
    ;;
  esac
  shift
done


# ---------------------------------------------------------------------
# From xft-config:

if test "$echo_prefix" = "yes" ; then
    echo $prefix
fi

if test "$echo_cflags" = "yes" ; then
    cflags="-I${includedir}  -pthread -std=c++11 -Wno-deprecated-declarations -m64 -I/home/beaujean/.local/sw/root/linux-ubuntu-14.04-x86_64/6.02.00/include/root"
    echo $cflags
fi

if test "$echo_libs" = "yes" ; then
    if test "${libdir}" != "/usr/lib" ; then
        echo -L${libdir} -lBAT -lBATmodels -lBATmtf -lBATmvc  -L/home/beaujean/.local/sw/root/linux-ubuntu-14.04-x86_64/6.02.00/lib/root -lCore -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMinuit -lRooFitCore -lRooFit -lRooStats -lFoam
    else
        echo -lBAT -lBATmodels -lBATmtf -lBATmvc  -L/home/beaujean/.local/sw/root/linux-ubuntu-14.04-x86_64/6.02.00/lib/root -lCore -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMinuit -lRooFitCore -lRooFit -lRooStats -lFoam
    fi
fi

# ---------------------------------------------------------------------


# EOF
