name: PublishDocs
on:
  push:
    branch:
      - master
jobs:
  # Build job
  build:
    # Specify runner +  build & upload the static files as an artifact
    runs-on: ubuntu-latest
    steps:
      - name: GetCode
        uses: actions/checkout@v3
      - name: Doxygenize
        # You may pin to the exact commit or the version.
        # uses: langroodi/doxygenize@542946a13bc9021f5ba07c8751e6ab3d84bca154
        uses: langroodi/doxygenize@v1.7.0
        with:
          # Doxygen configuration file path
          doxygenconf: ./Doxygen/Doxyfile-master

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: build_outputs_folder/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
