#!/bin/bash

## NOTE: Uncomment lines 5, 24-26 to run the configurations after specifying EXEPATH below.

# EXEPATH=<PATH TO ANALYSIS>
RD_array=(0.31 0.34 0.37 0.40657)
RD_ERR=0.0464463
RDst_array=(0.26 0.275 0.29 0.30560)
RDst_ERR=0.0151498

for i in AllInfo Lattice UTfit
do
        cd ${i}
        for j in ${!RD_array[*]}
        do
		dir=SM_RD_${RD_array[${j}]}_RDst_${RDst_array[${j}]}
		rm -rf ${dir}
		mkdir -p ${dir}/config
                cp ../MonteCarlo.conf ${dir}/config
                cp config_CLN_${i}/*.conf ${dir}/config
                cd ${dir}
		sed -i.bak -e "s/MEAN_RDst/${RDst_array[${j}]}/" -e "s/ERRG_RDst/${RDst_ERR}/" -e "s/MEAN_RD/${RD_array[${j}]}/" -e "s/ERRG_RD/${RD_ERR}/" config/Observables.conf
                rm -f *.out *.err log.txt *.pdf. *.root *.tex *.txt config/*.bak
#                ln -sf ${EXEPATH} .
#                sed -e "s#NAME#CLN-${i}-${j}#g" ../../sbatch.sh sbatch.sh
#                sbatch sbatch.sh
                cd ..
        done
        cd ..
done

for i in AllInfo Lattice UTfit
do
        cd ${i}
        for j in SM SM_D SM_Dst
        do
                cp ../MonteCarlo.conf ${j}/config
                cd ${j}
                rm -f *.out *.err log.txt *.pdf. *.root *.tex *.txt
#                ln -sf ${EXEPATH} .
#                sed -e "s#NAME#CLN-${i}-${j}#g" ../../sbatch.sh sbatch.sh
#                sbatch sbatch.sh
                cd ..
        done
        cd ..
done
