#!/bin/bash

#######################################################################################
## Create a directory called WORK (or anything) at the level of the Configurations   ##
## folder and put this script there and run it. It is both Linux and Mac compatible. ##
## Comment out the sbatch sbatch.sh line to suppress the submission command.         ##
##                                                                                   ##
## -- Ayan Paul (Nov 2018, Berlin)                                                   ##
#######################################################################################

# This works for ILC only #

col="ILC"
vCOL=$1
DOM=""
BATCH="CONDOR"
if [ ${BATCH} == 'SLURM' ]; then
    EXE="/home/apaul/NetBeansProjects/HEPfit-B1/Analysis/dist/Debug_MPI/GNU-Linux/analysis"
elif [ ${BATCH} == 'CONDOR' ]; then
    EXE="/afs/desy.de/user/a/apaul/NetBeansProjects/HEPfit/Analysis/dist/Release_MPI/Intel-Linux/analysis"
fi

mkdir -p ${col}${vCOL}
cd ${col}${vCOL}


for l in UP P1 P2
do
    mkdir -p ${l} && cd ${l}
    mkdir -p Fit_${col}_HLLHC_{noZpole,ExactEW}_{S1,S2}_{E1,E2,E3}_${l}
    for k in E1 E2 E3
    do
	for j in S1 S2
	do
	    for i in Fit_${col}_HLLHC_noZpole_${j}_${k}_${l} Fit_${col}_HLLHC_ExactEW_${j}_${k}_${l}
	    do
		cd ${i}
		rm -rf config && mkdir config
		cp ../../../../Configurations/config_${col}/*.conf config/.
		cp ../../../../Configurations/config_${col}/config_${l}/*.conf config/.
		cp ../../../../Configurations/config_HLLHC/*_${j}.conf config/.
		cp ../../../../Configurations/config_HLLHC/aTGC${DOM}_observables_HLLHC_Full.conf config/.
		mv config/MonteCarlo-${BATCH}.conf config/MonteCarlo.conf
		rm -f config/MonteCarlo-*.conf	    
		sed -i.bak -e "/_${j}.conf/s/^# //" -e "/HLLHC_Full.conf/s/^# //" -e "/HLLHC_Full.conf/s/aTGC/aTGC${DOM}/" -e "/observables_ILC/s/aTGC/aTGC${DOM}/" -e "s/POLR/${l}/" config/model.conf
		sed -i.bak -e "s/#HLLHC# //" -e "/CuH_33r/s/HLLHC/5.0/" config/model.conf
		if [ ${k} == 'E2' ]
		then
		    sed -i.bak -e "/ILC_350/s/^# //" config/model.conf
		    sed -i.bak -e "s/#350# //" config/ObservablesHiggs_ILC_${l}.conf
		    rm config/*_500*.conf
		elif [ ${k} == 'E3' ]
		then
	    	    sed -i.bak -e "/ILC_350/s/^# //" config/model.conf
		    sed -i.bak -e "s/#350# //" config/ObservablesHiggs_ILC_${l}.conf
		    sed -i.bak -e "/ILC_500/s/^# //" config/model.conf
		    sed -i.bak -e "s/#500# //" config/ObservablesHiggs_ILC_${l}.conf
		elif [ ${k} == 'E1' ]
		then
		    rm config/*_350*.conf config/*_500*.conf
		fi
		case ${i} in 
		    Fit_${col}_HLLHC_Zpole_${j}_${k}_${l})
			cp ../../../../Configurations/config_HLLHC/ObservablesEW_HLLHC.conf config/.
			sed -i.bak -e "s/#QUARK# //" -e "/CHd_/s/QUARK/3.0/" -e "s/QUARK/1.0/" config/model.conf
			sed -i.bak -e "s/#ZPOLE# //" -e "s/ZPOLE_L/2.0e-2/" -e "s/ZPOLE/3.0e-2/" -e "s/#EWP# //" config/model.conf
			sed -i.bak -e "s/#EW# //" -e "s/13/28/" config/NPcouplings.conf
			;;
		    Fit_${col}_HLLHC_noZpole_${j}_${k}_${l})
			cp ../../../../Configurations/config_HLLHC/ObservablesEW_HLLHC.conf config/.
			sed -i.bak -e "s/#QUARK# //" -e "s/QUARK_L/3.0/" -e "s/QUARK/1.0/" config/model.conf
			sed -i.bak -e "s/#ZPOLE# //" -e "s/ZPOLE_L/1.2e-1/" -e "s/ZPOLE/3.0e-2/" -e "s/#EWP# //" -e "/_${col}_Zpole/s/^/# /" config/model.conf
			sed -i.bak -e "s/#EW# //" -e "s/13/28/" config/NPcouplings.conf
			;;
		    Fit_${col}_HLLHC_ExactEW_${j}_${k}_${l})
			sed -i.bak -e "s/#QUARK# //" -e "s/QUARK_L/0./" -e "s/QUARK/0./" config/model.conf
			sed -i.bak -e "s/#ZPOLE# //" -e "s/ZPOLE_L/0./" -e "s/ZPOLE/0./" config/model.conf
			sed -i.bak -e "/ObservablesEW/s/^/# /" config/model.conf
			mv config/SMparameters-noerror.conf config/SMparameters.conf
			;;
		esac
		rm -f config/*.bak config/SMparameters-noerror.conf analysis *.out *.err
		ln -s ${EXE} .
		#./analysis config/model.conf --noMC
		if [ ${BATCH} == 'SLURM' ]; then
            	    sed -e "s/NAME/${l}_${i}/" ../../../../Configurations/sbatch.sh > sbatch.sh
            	    sbatch sbatch.sh
		elif [ ${BATCH} == 'CONDOR' ]; then
            	    sed -e "/FAME/s/NAME/${l}_${i}/" ../../../../Configurations/submit_condor.sh > submit_condor.sh
            	    sed -e "s#WORK_DIR#ILC${vCOL}/${l}/${i}#" ../../../../Configurations/mpi-wrap.sh > mpi-wrap.sh
            	    condor_submit submit_condor.sh
		fi
		cd ..
	    done
	done
    done
    cd ..
done

for l in UP P1 P2
do
    mkdir -p ${l} && cd ${l}
    mkdir -p Fit_${col}_{noZpole,ExactEW}_{E1,E2,E3}_${l}
    for k in E1 E2 E3
    do
	for i in Fit_${col}_noZpole_${k}_${l} Fit_${col}_ExactEW_${k}_${l} 
	do
	    cd ${i}
	    rm -rf config && mkdir config
	    cp ../../../../Configurations/config_${col}/*.conf config/.
	    cp ../../../../Configurations/config_${col}/config_${l}/*.conf config/.
	    mv config/MonteCarlo-${BATCH}.conf config/MonteCarlo.conf
	    rm -f config/MonteCarlo-*.conf
	    if [ ${k} == 'E2' ]
	    then
		sed -i.bak -e "/ILC_350/s/^# //" config/model.conf
		sed -i.bak -e "s/#350# //" config/ObservablesHiggs_ILC_${l}.conf
		rm config/*_500*.conf
	    elif [ ${k} == 'E3' ]
	    then
		sed -i.bak -e "/ILC_350/s/^# //" config/model.conf
		sed -i.bak -e "s/#350# //" config/ObservablesHiggs_ILC_${l}.conf
		sed -i.bak -e "/ILC_500/s/^# //" config/model.conf
		sed -i.bak -e "s/#500# //" config/ObservablesHiggs_ILC_${l}.conf
	    elif [ ${k} == 'E1' ]
	    then
		rm config/*_350*.conf config/*_500*.conf
	    fi
	    sed -i.bak -e "/CuH_33r/s/#HLLHC# //" -e "/CuH_33r/s/HLLHC/0./" -e "/observables_ILC/s/aTGC/aTGC${DOM}/" -e "s/POLR/${l}/" config/model.conf
	    case ${i} in
		Fit_${col}_Zpole_${k}_${l})
		    sed -i.bak -e "s/#QUARK# //" -e "s/QUARK_L/3.0/" -e "s/QUARK/1.0/" config/model.conf
		    sed -i.bak -e "s/#ZPOLE# //" -e "s/ZPOLE_L/6.0e-2/" -e "s/ZPOLE/3.0e-2/" -e "s/#EWP# //" config/model.conf
		    sed -i.bak -e "s/#EW# //" -e "s/13/28/" config/NPcouplings.conf
		    ;;
		Fit_${col}_noZpole_${k}_${l})
		    sed -i.bak -e "s/#QUARK# //" -e "s/QUARK_L/3.0/" -e "s/QUARK/1.0/" config/model.conf
		    sed -i.bak -e "s/#ZPOLE# //" -e "s/ZPOLE_L/1.5e-1/" -e "s/ZPOLE/1.5e-1/" -e "s/#EWP# //" -e "/_${col}_Zpole/s/^/# /" config/model.conf
		    sed -i.bak -e "s/#EW# //" -e "s/13/28/" config/NPcouplings.conf
		    ;;
		Fit_${col}_ExactEW_${k}_${l})
		    sed -i.bak -e "s/#ZPOLE# //" -e "s/ZPOLE_L/0./" -e "s/ZPOLE/0./" config/model.conf
		    sed -i.bak -e "s/#QUARK# //" -e "s/QUARK_L/0./" -e "s/QUARK/0./" config/model.conf
		    sed -i.bak -e "/ObservablesEW/s/^/# /" config/model.conf
		    mv config/SMparameters-noerror.conf config/SMparameters.conf
		    ;;
	    esac
	    rm -f config/*.bak config/SMparameters-noerror.conf analysis *.out *.err
	    ln -s ${EXE} .
	    #./analysis config/model.conf --noMC
	    if [ ${BATCH} == 'SLURM' ]; then
		sed -e "s/NAME/${l}_${i}/" ../../../../Configurations/sbatch.sh > sbatch.sh
		sbatch sbatch.sh
            elif [ ${BATCH} == 'CONDOR' ]; then
		sed -e "/FAME/s/NAME/${l}_${i}/" ../../../../Configurations/submit_condor.sh > submit_condor.sh
		sed -e "s#WORK_DIR#ILC${vCOL}/${l}/${i}#" ../../../../Configurations/mpi-wrap.sh > mpi-wrap.sh
		condor_submit submit_condor.sh
            fi
	    cd ..
	done
    done
    cd ..
done
